### ISSUE TITLE
Expand closes when expanded is set to false

### ISSUE THREAD

**Issue by Thymas1** [staccx/bento#14]
Please provide details about:

controlled expand that allowed us to close expand onClick 

example 
<Expand>
   <span>heading </span>
  <Button onClick={() => setExpand(false)}>Button</Button>
</Expand>

**Comment by XSlemX** [comment]
How about a prop `closeOnItemClicked`?

**Comment by XSlemX** [comment]
In addition to allowing controlled behaviour, that is. It should respect the change of `expanded` prop
