### ISSUE TITLE
SliderKeyboardInput: Update value while dragging

### ISSUE THREAD

**Issue by robinsandborg** [staccx/bento#15]
Should SliderKeyboardInput change/show the value of the input while dragging? The current solution makes it hard to know where along the track you should release to get the value you want.

See [DNB](https://www.dnb.no/privat/laan/kalkulator/boliglaan.html) for an example of a slider that does this.

It might be necessary to add some throttling or debouncing to the slider in order to limit the number of updates while dragging fast. DNB also seems to have implemented this behaviour.

**Comment by robinsandborg** [comment]
Current implementation has one issue. The component should not run it's onChange function until the slider is released.

The input should change its value, but this information should be kept locally in the component until the slider is released.

The current implementation sends a lot of events, and in the case where the sliders value is connected to calling an API, there are some issues.

**Comment by XSlemX** [comment]
Fixed in 32135434f615b0676e1592f4720beb85418139c8
