### ISSUE TITLE
CheckGroup returns an array of all RadioButtons that has been clicked

### ISSUE THREAD

**Issue by Thymas1** [staccx/bento#17]
CheckGroup returns an array of all clicked item inside the checkGroup and not just the selected RadioButton. 
Every time you click on a RadioButton, the array increases.

**Comment by robinsandborg** [comment]
Looks like the last version only worked with radiobuttons and the new version now only works with checkboxes. Supporting both or creating two different components (CheckGroup/RadioGroup) would be good.

**Comment by XSlemX** [comment]
I think a new `<RadioGroup />` is needed.

**Comment by Thymas1** [comment]
Good point made by @XSlemX give RadioButton a name and onChange and remove CheckGroup around them, works fine 👍
