### ISSUE TITLE
TranslateDebug fails when value is structured content

### ISSUE THREAD

**Issue by XSlemX** [staccx/bento#42]
## The problem
When using the debug flag i i18nProvider and trying to render a `<Translate>` it fails if the key refer to structured content (aka RichText aka SanityContent).

## Environment

* Bento version: >13.0
* Last Bento version that did not exhibit the issue (if applicable): 12.1.0
* Node.js version: 15.10.0
* Npm or Yarn package manager: 1.22.5
* Mobile platform/version under test: n/a

## Details

See the story `Translate/Structured Content`. The reason why this happens is that TranslateDebug assumes the value is always a string, which it is not.

**Comment by Thymas1** [comment]
https://github.com/staccx/bento/pull/43
Pull request to fix bug
