### ISSUE TITLE
Improvements to createVariants

### ISSUE THREAD

**Issue by robinsandborg** [staccx/bento#5]
The current way of creating variants looks like this:
```
export const expandBtnVariants = createVariants(
  {
    [VARIANT_DEFAULT]: css``,
    primary: css``
  },
  Expand.themeProps.button.name
)

export const expandItemVariants = createVariants(
  {
    [VARIANT_DEFAULT]: css``
  },
  Expand.themeProps.item.name
)

export const expandIconVariants = createVariants(
  {
    [VARIANT_DEFAULT]: css``
  },
  Expand.themeProps.icon.name
)
```

Instead of calling the createVariants function one time per themeProp, it would be nice to be able to just call it once per component. Something like this might be a nice improvement:

```
Expand.createVariants({
  button: {
    [VARIANT_DEFAULT]: css``,
    primary: css``
  },
  item: {
    [VARIANT_DEFAULT]: css``
  },
  icon: {
    [VARIANT_DEFAULT]: css``
  }
})
```

In addition to requiring less code, this approach would enable us to create new variants for new themePropsn without importing new items into the theme and adding them. This will greatly reduce the friction when adding new themeprop variants.

**Comment by XSlemX** [comment]
The one problem with this approach is the themeprops. You would have to know the name of them when creating the variants. I do like the syntax, though.

**Comment by robinsandborg** [comment]
It would be nice to not need to know them, but this is an issue we have with the current way of doint it as well, so I don't see why that should be a show stopper

**Comment by XSlemX** [comment]
> Or does your IDE suggest these for you? Mine does, but not in a very useful way since it gives me tons of other options as well.

It cannot be that smart? You are creating a new object, and the suggestions it is producing must be "best guess"!?

> Anyway, having to add a new import and remembering to add that import to the theme each time you target a new themeprop is really annoying.

What do you mean? What do you have to import when targeting a new themeprop?

**Comment by robinsandborg** [comment]
Writing this stuff is a bit of a hassle:

```
import {
  RadioButtonWrapper,
  RadioButtonLabel,
  RadioButtonInput
} from "./variants/variants.RadioButton"

Theme({}).add([RadioButtonWrapper, RadioButtonLabel, RadioButtonInput])
```

If all variants were created in just one function, I wouldn't need to remember to import the new themeProp variants into the theme

**Comment by XSlemX** [comment]
I see! I will think on it.

**Comment by XSlemX** [comment]
This was added to bento. 

See new readme for info
